In [1]:
#importing pandas
import pandas as pd

In [2]:
#defining the file path
csv_path = "../CSVs/indicators-CountiesUAsfromApr2021.data.csv"

In [3]:
#converting to dataframe
df = pd.read_csv(csv_path)
df.T

,0,1,2,3,4,5,6,7,8,9,...,16360,16361,16362,16363,16364,16365,16366,16367,16368,16369
Indicator ID,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001,...,93765,93765,93765,93765,93765,93765,93765,93765,93765,93765
Indicator Name,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...,Admission episodes for alcohol-related conditi...
Parent Code,NaN,NaN,NaN,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,...,E12000003,E12000004,E12000008,E12000009,E12000005,E12000006,E12000008,E12000005,E12000008,E12000005
Parent Name,NaN,NaN,NaN,England,England,England,England,England,England,England,...,Yorkshire and the Humber region,East Midlands region,South East region,South West region,West Midlands region,East of England region,South East region,West Midlands region,South East region,West Midlands region
Area Code,E92000001,E92000001,E92000001,E12000001,E12000002,E12000003,E12000004,E12000005,E12000006,E12000007,...,E10000023,E10000024,E10000025,E10000027,E10000028,E10000029,E10000030,E10000031,E10000032,E10000034
Area Name,England,England,England,North East region,North West region,Yorkshire and the Humber region,East Midlands region,West Midlands region,East of England region,London region,...,North Yorkshire,Nottinghamshire,Oxfordshire,Somerset,Staffordshire,Suffolk,Surrey,Warwickshire,West Sussex,Worcestershire
Area Type,England,England,England,Region,Region,Region,Region,Region,Region,Region,...,Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021)
Sex,Male,Female,Persons,Male,Male,Male,Male,Male,Male,Male,...,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons
Age,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,...,All ages,All ages,All ages,All ages,All ages,All ages,All ages,All ages,All ages,All ages
Category Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,...,2020/21,2020/21,2020/21,2020/21,2020/21,2020/21,2020/21,2020/21,2020/21,2020/21
Value,15.854079,5.100815,10.262062,18.757709,17.055883,15.717887,15.87285,16.722838,14.70627,14.922064,...,1368.764184,1542.102497,1200.359467,1471.726282,1622.487636,1245.115668,1253.441861,1543.447486,1208.623302,1429.24421
Lower CI 95.0 limit,15.535398,4.929587,10.087435,17.211115,16.173375,14.738587,14.802591,15.727444,13.788505,14.07392,...,1341.084878,1515.930943,1174.232306,1441.318545,1596.72914,1220.987085,1233.284305,1512.011415,1186.259406,1400.020096
Upper CI 95.0 limit,16.177504,5.276441,10.438934,20.401151,17.97318,16.744151,16.998605,17.763208,15.667867,15.804693,...,1396.86251,1568.611075,1226.920162,1502.604311,1648.55554,1269.596581,1273.8451,1575.37075,1231.299475,1458.921011
Lower CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1325.317579,1500.995215,1159.366682,1424.001612,1582.018834,1207.236463,1221.774257,1494.109314,1173.50787,1383.377548
Upper CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1413.179665,1583.989186,1242.354586,1520.538358,1663.672028,1283.809578,1285.677666,1593.912139,1244.460856,1476.15757
Count,10004.0,3398.0,13402.0,595.0,1465.0,999.0,858.0,1122.0,1007.0,1379.0,...,9676.06,13338.84,8066.5,9273.48,15315.82,10393.57,14878.95,9235.95,11358.24,9245.03
Denominator,63683865.0,67400167.0,131084032.0,3249450.0,8645595.0,6372964.0,5459090.0,6791370.0,6981250.0,9442686.0,...,620610.0,833377.0,696880.0,563851.0,883172.0,761246.0,1199870.0,583786.0,867635.0,598070.0
Value note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Recent Trend,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,No significant change,Cannot be calculated,No significant change,No significant change,Increasing and getting worse,No significant change,No significant change,Increasing and getting worse,No significant change,No significant change
Compared to England value or percentiles,Not compared,Not compared,Not compared,Worse,Worse,Similar,Similar,Similar,Better,Better,...,Better,Worse,Better,Similar,Worse,Better,Better,Worse,Better,Better
Compared to Region value or percentiles,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,...,Better,Worse,Better,Similar,Better,Similar,Better,Better,Better,Better
Time period Sortable,20010000,20010000,20010000,20010000,20010000,20010000,20010000,20010000,20010000,20010000,...,20200000,20200000,20200000,20200000,20200000,20200000,20200000,20200000,20200000,20200000
New data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Compared to goal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period range,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y,...,1y,1y,1y,1y,1y,1y,1y,1y,1y,1y

In [4]:
#getting rid of non-suicide data
non_suicide = []

for x in range(len(df)):
    if df["Indicator Name"][x] != "Suicide rate":
        non_suicide.append(x)

In [5]:
#creating a dataframe from that
cleaned_df = df.drop(non_suicide)
cleaned_df.reset_index(drop=True,inplace = True)
cleaned_df.T

,0,1,2,3,4,5,6,7,8,9,...,9352,9353,9354,9355,9356,9357,9358,9359,9360,9361
Indicator ID,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001,...,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001
Indicator Name,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,...,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate
Parent Code,NaN,NaN,NaN,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,...,E12000003,E12000004,E12000008,E12000009,E12000005,E12000006,E12000008,E12000005,E12000008,E12000005
Parent Name,NaN,NaN,NaN,England,England,England,England,England,England,England,...,Yorkshire and the Humber region,East Midlands region,South East region,South West region,West Midlands region,East of England region,South East region,West Midlands region,South East region,West Midlands region
Area Code,E92000001,E92000001,E92000001,E12000001,E12000002,E12000003,E12000004,E12000005,E12000006,E12000007,...,E10000023,E10000024,E10000025,E10000027,E10000028,E10000029,E10000030,E10000031,E10000032,E10000034
Area Name,England,England,England,North East region,North West region,Yorkshire and the Humber region,East Midlands region,West Midlands region,East of England region,London region,...,North Yorkshire,Nottinghamshire,Oxfordshire,Somerset,Staffordshire,Suffolk,Surrey,Warwickshire,West Sussex,Worcestershire
Area Type,England,England,England,Region,Region,Region,Region,Region,Region,Region,...,Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021)
Sex,Male,Female,Persons,Male,Male,Male,Male,Male,Male,Male,...,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons
Age,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,...,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs
Category Type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,2001 - 03,...,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21
Value,15.854079,5.100815,10.262062,18.757709,17.055883,15.717887,15.87285,16.722838,14.70627,14.922064,...,11.34388,10.288874,10.032477,15.054165,11.910169,10.387505,10.096817,11.215052,11.533312,12.015792
Lower CI 95.0 limit,15.535398,4.929587,10.087435,17.211115,16.173375,14.738587,14.802591,15.727444,13.788505,14.07392,...,9.662695,8.940983,8.566038,13.018703,10.498337,8.958705,8.978991,9.531937,10.130841,10.274342
Upper CI 95.0 limit,16.177504,5.276441,10.438934,20.401151,17.97318,16.744151,16.998605,17.763208,15.667867,15.804693,...,13.025065,11.636765,11.498917,17.089627,13.322,11.816305,11.214644,12.898167,12.935783,13.757243
Lower CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Upper CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Count,10004.0,3398.0,13402.0,595.0,1465.0,999.0,858.0,1122.0,1007.0,1379.0,...,183.0,226.0,181.0,219.0,277.0,208.0,316.0,172.0,265.0,186.0
Denominator,63683865.0,67400167.0,131084032.0,3249450.0,8645595.0,6372964.0,5459090.0,6791370.0,6981250.0,9442686.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Value note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Recent Trend,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated
Compared to England value or percentiles,Not compared,Not compared,Not compared,Worse,Worse,Similar,Similar,Similar,Better,Better,...,Similar,Similar,Similar,Worse,Worse,Similar,Similar,Similar,Similar,Similar
Compared to Region value or percentiles,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,...,Similar,Similar,Similar,Worse,Similar,Similar,Similar,Similar,Similar,Similar
Time period Sortable,20010000,20010000,20010000,20010000,20010000,20010000,20010000,20010000,20010000,20010000,...,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000
New data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Compared to goal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period range,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y,...,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y

In [6]:
#getting rid of data from before the 2017-19 period
not_app = []

for x in range(len(cleaned_df)):
    if cleaned_df["Time period"][x] != "2019 - 21" and cleaned_df["Time period"][x] != "2017 - 19":
        not_app.append(x)

In [7]:
#turning that into a dataframe
applicable_df = cleaned_df.drop(not_app)
applicable_df.reset_index(drop=True, inplace = True)
applicable_df.T

,0,1,2,3,4,5,6,7,8,9,...,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095
Indicator ID,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001,...,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001
Indicator Name,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,...,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate
Parent Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,E12000003,E12000004,E12000008,E12000009,E12000005,E12000006,E12000008,E12000005,E12000008,E12000005
Parent Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yorkshire and the Humber region,East Midlands region,South East region,South West region,West Midlands region,East of England region,South East region,West Midlands region,South East region,West Midlands region
Area Code,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,...,E10000023,E10000024,E10000025,E10000027,E10000028,E10000029,E10000030,E10000031,E10000032,E10000034
Area Name,England,England,England,England,England,England,England,England,England,England,...,North Yorkshire,Nottinghamshire,Oxfordshire,Somerset,Staffordshire,Suffolk,Surrey,Warwickshire,West Sussex,Worcestershire
Area Type,England,England,England,England,England,England,England,England,England,England,...,Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021)
Sex,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male,...,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons
Age,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,...,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs
Category Type,NaN,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,NaN,Most deprived decile (IMD2019),Second most deprived decile (IMD2019),Third more deprived decile (IMD2019),Fourth more deprived decile (IMD2019),Fifth more deprived decile (IMD2019),Fifth less deprived decile (IMD2019),Fourth less deprived decile (IMD2019),Third less deprived decile (IMD2019),Second least deprived decile (IMD2019),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,...,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21
Value,15.5,16.233048,16.681435,15.698346,15.485131,16.368517,16.58227,15.454581,16.113469,14.189319,...,11.34388,10.288874,10.032477,15.054165,11.910169,10.387505,10.096817,11.215052,11.533312,12.015792
Lower CI 95.0 limit,15.2,15.22764,15.462473,14.69,14.445982,15.393446,15.620384,14.683598,15.271178,13.467439,...,9.662695,8.940983,8.566038,13.018703,10.498337,8.958705,8.978991,9.531937,10.130841,10.274342
Upper CI 95.0 limit,15.8,17.238456,17.900397,16.706692,16.524281,17.343587,17.544157,16.225564,16.955761,14.911199,...,13.025065,11.636765,11.498917,17.089627,13.322,11.816305,11.214644,12.898167,12.935783,13.757243
Lower CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Upper CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Count,11145.0,1055.0,735.0,979.0,896.0,1100.0,1149.0,1555.0,1415.0,1493.0,...,183.0,226.0,181.0,219.0,277.0,208.0,316.0,172.0,265.0,186.0
Denominator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Value note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Recent Trend,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated
Compared to England value or percentiles,Not compared,Similar,Similar,Similar,Similar,Similar,Worse,Similar,Similar,Better,...,Similar,Similar,Similar,Worse,Worse,Similar,Similar,Similar,Similar,Similar
Compared to Region value or percentiles,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,...,Similar,Similar,Similar,Worse,Similar,Similar,Similar,Similar,Similar,Similar
Time period Sortable,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,...,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000
New data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Compared to goal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period range,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y,...,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y

In [8]:
#splitting the data into pre and during covid
pre_covid = []

for x in range(len(applicable_df)):
    if applicable_df["Time period"][x] == "2017 - 19":
        pre_covid.append(x)

covid = []

for x in range(len(applicable_df)):
    if applicable_df["Time period"][x] == "2019 - 21":
        covid.append(x)

In [9]:
#creating dataframes from that
covid_times = applicable_df.drop(pre_covid)
pre_covid_times = applicable_df.drop(covid)

In [10]:
#resetting the index
covid_times.reset_index(drop=True,inplace = True)
pre_covid_times.reset_index(drop=True,inplace = True)
pre_covid_times.T

,0,1,2,3,4,5,6,7,8,9,...,540,541,542,543,544,545,546,547,548,549
Indicator ID,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001,...,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001
Indicator Name,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,...,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate
Parent Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,E12000003,E12000004,E12000008,E12000009,E12000005,E12000006,E12000008,E12000005,E12000008,E12000005
Parent Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yorkshire and the Humber region,East Midlands region,South East region,South West region,West Midlands region,East of England region,South East region,West Midlands region,South East region,West Midlands region
Area Code,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,...,E10000023,E10000024,E10000025,E10000027,E10000028,E10000029,E10000030,E10000031,E10000032,E10000034
Area Name,England,England,England,England,England,England,England,England,England,England,...,North Yorkshire,Nottinghamshire,Oxfordshire,Somerset,Staffordshire,Suffolk,Surrey,Warwickshire,West Sussex,Worcestershire
Area Type,England,England,England,England,England,England,England,England,England,England,...,Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021)
Sex,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male,...,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons
Age,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,...,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs
Category Type,NaN,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,NaN,Most deprived decile (IMD2019),Second most deprived decile (IMD2019),Third more deprived decile (IMD2019),Fourth more deprived decile (IMD2019),Fifth more deprived decile (IMD2019),Fifth less deprived decile (IMD2019),Fourth less deprived decile (IMD2019),Third less deprived decile (IMD2019),Second least deprived decile (IMD2019),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,...,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19,2017 - 19
Value,15.5,16.233048,16.681435,15.698346,15.485131,16.368517,16.58227,15.454581,16.113469,14.189319,...,12.251956,9.135405,8.94765,13.065772,11.540015,9.531723,8.180909,9.382023,9.678995,10.479799
Lower CI 95.0 limit,15.2,15.22764,15.462473,14.69,14.445982,15.393446,15.620384,14.683598,15.271178,13.467439,...,10.497392,7.860801,7.563524,11.155228,10.143951,8.156556,7.1732,7.838246,8.376794,8.864068
Upper CI 95.0 limit,15.8,17.238456,17.900397,16.706692,16.524281,17.343587,17.544157,16.225564,16.955761,14.911199,...,14.006519,10.410009,10.331776,14.976315,12.93608,10.906889,9.188619,10.9258,10.981196,12.09553
Lower CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Upper CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Count,11145.0,1055.0,735.0,979.0,896.0,1100.0,1149.0,1555.0,1415.0,1493.0,...,195.0,199.0,162.0,186.0,266.0,188.0,255.0,143.0,216.0,164.0
Denominator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Value note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Recent Trend,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Compared to England value or percentiles,Not compared,Similar,Similar,Similar,Similar,Similar,Worse,Similar,Similar,Better,...,Worse,Similar,Similar,Worse,Worse,Similar,Better,Similar,Similar,Similar
Compared to Region value or percentiles,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,...,Similar,Similar,Similar,Similar,Similar,Similar,Better,Similar,Similar,Similar
Time period Sortable,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,...,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000,20170000
New data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Compared to goal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period range,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y,...,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y

In [11]:
covid_times.T

,0,1,2,3,4,5,6,7,8,9,...,536,537,538,539,540,541,542,543,544,545
Indicator ID,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001,...,41001,41001,41001,41001,41001,41001,41001,41001,41001,41001
Indicator Name,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,...,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate,Suicide rate
Parent Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,E12000003,E12000004,E12000008,E12000009,E12000005,E12000006,E12000008,E12000005,E12000008,E12000005
Parent Name,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yorkshire and the Humber region,East Midlands region,South East region,South West region,West Midlands region,East of England region,South East region,West Midlands region,South East region,West Midlands region
Area Code,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,E92000001,...,E10000023,E10000024,E10000025,E10000027,E10000028,E10000029,E10000030,E10000031,E10000032,E10000034
Area Name,England,England,England,England,England,England,England,England,England,England,...,North Yorkshire,Nottinghamshire,Oxfordshire,Somerset,Staffordshire,Suffolk,Surrey,Warwickshire,West Sussex,Worcestershire
Area Type,England,England,England,England,England,England,England,England,England,England,...,Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021),Counties & UAs (from Apr 2021)
Sex,Male,Male,Male,Male,Male,Male,Male,Male,Male,Male,...,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons,Persons
Age,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,...,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs,10+ yrs
Category Type,NaN,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,County & UA deprivation deciles in England (IM...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,NaN,Most deprived decile (IMD2019),Second most deprived decile (IMD2019),Third more deprived decile (IMD2019),Fourth more deprived decile (IMD2019),Fifth more deprived decile (IMD2019),Fifth less deprived decile (IMD2019),Fourth less deprived decile (IMD2019),Third less deprived decile (IMD2019),Second least deprived decile (IMD2019),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,...,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21,2019 - 21
Value,15.895012,17.029486,16.942727,15.674408,15.637476,16.093949,16.317297,18.001344,15.307912,14.20416,...,11.34388,10.288874,10.032477,15.054165,11.910169,10.387505,10.096817,11.215052,11.533312,12.015792
Lower CI 95.0 limit,15.603845,16.013804,15.730116,14.678297,14.602315,15.136144,15.397221,17.145219,14.501145,13.485446,...,9.662695,8.940983,8.566038,13.018703,10.498337,8.958705,8.978991,9.531937,10.130841,10.274342
Upper CI 95.0 limit,16.186178,18.045168,18.155337,16.670519,16.672637,17.051753,17.237374,18.857469,16.114679,14.922874,...,13.025065,11.636765,11.498917,17.089627,13.322,11.816305,11.214644,12.898167,12.935783,13.757243
Lower CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Upper CI 99.8 limit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Count,11551.0,1137.0,761.0,997.0,911.0,1097.0,1216.0,1711.0,1391.0,1510.0,...,183.0,226.0,181.0,219.0,277.0,208.0,316.0,172.0,265.0,186.0
Denominator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Value note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Recent Trend,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,...,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated,Cannot be calculated
Compared to England value or percentiles,Not compared,Worse,Similar,Similar,Similar,Similar,Similar,Worse,Similar,Better,...,Similar,Similar,Similar,Worse,Worse,Similar,Similar,Similar,Similar,Similar
Compared to Region value or percentiles,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,Not compared,...,Similar,Similar,Similar,Worse,Similar,Similar,Similar,Similar,Similar,Similar
Time period Sortable,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,...,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000,20190000
New data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Compared to goal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Time period range,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y,...,3y,3y,3y,3y,3y,3y,3y,3y,3y,3y

In [12]:
#a list for the columns that are going to be dropped
drop_col = ["Indicator ID", "Indicator Name", "Parent Code", "Area Code", "Category Type", "Age","Lower CI 95.0 limit", "Upper CI 95.0 limit", "Lower CI 99.8 limit", "Upper CI 99.8 limit", "Denominator", "Value note", "Recent Trend", "Time period Sortable", "New data", "Compared to goal", "Time period range"]

In [13]:
#dropping the columns
pre_covid_times.drop(columns = drop_col, inplace = True)
covid_times.drop(columns = drop_col, inplace = True)

In [14]:
pre_covid_times.head()

,Parent Name,Area Name,Area Type,Sex,Category,Time period,Value,Count,Compared to England value or percentiles,Compared to Region value or percentiles
0,NaN,England,England,Male,NaN,2017 - 19,15.500000,11145.0,Not compared,Not compared
1,NaN,England,England,Male,Most deprived decile (IMD2019),2017 - 19,16.233048,1055.0,Similar,Not compared
2,NaN,England,England,Male,Second most deprived decile (IMD2019),2017 - 19,16.681435,735.0,Similar,Not compared
3,NaN,England,England,Male,Third more deprived decile (IMD2019),2017 - 19,15.698346,979.0,Similar,Not compared
4,NaN,England,England,Male,Fourth more deprived decile (IMD2019),2017 - 19,15.485131,896.0,Similar,Not compared

In [15]:
covid_times.head()

,Parent Name,Area Name,Area Type,Sex,Category,Time period,Value,Count,Compared to England value or percentiles,Compared to Region value or percentiles
0,NaN,England,England,Male,NaN,2019 - 21,15.895012,11551.0,Not compared,Not compared
1,NaN,England,England,Male,Most deprived decile (IMD2019),2019 - 21,17.029486,1137.0,Worse,Not compared
2,NaN,England,England,Male,Second most deprived decile (IMD2019),2019 - 21,16.942727,761.0,Similar,Not compared
3,NaN,England,England,Male,Third more deprived decile (IMD2019),2019 - 21,15.674408,997.0,Similar,Not compared
4,NaN,England,England,Male,Fourth more deprived decile (IMD2019),2019 - 21,15.637476,911.0,Similar,Not compared

In [16]:
#putting those dataframes to csvs
pre_covid_times.to_csv("../CSVs/PreCovid.csv", index=False)
covid_times.to_csv("../CSVs/DuringCovid.csv", index=False)

In [17]:
#getting rid of data not needed for specific questions (regions and areas) and making dataframes from that
not_region = []

for x in range(len(covid_times)):
    if covid_times["Area Type"][x] != "Region" or covid_times["Sex"][x] != "Persons":
        not_region.append(x)

not_area = []

for x in range(len(covid_times)):
    if covid_times["Area Type"][x] != "Counties & UAs (from Apr 2021)" or covid_times["Sex"][x] != "Persons":
        not_area.append(x)

covid_regions = covid_times.drop(not_region)
covid_areas = covid_times.drop(not_area)
covid_regions.reset_index(drop=True, inplace=True)
covid_areas.reset_index(drop=True, inplace=True)
covid_regions.drop(columns = ["Sex", "Category", "Parent Name", "Area Type", "Compared to Region value or percentiles"], inplace = True)
covid_areas.drop(columns = ["Sex", "Category", "Area Type"], inplace = True)

not_region = []

for x in range(len(pre_covid_times)):
    if pre_covid_times["Area Type"][x] != "Region" or pre_covid_times["Sex"][x] != "Persons":
        not_region.append(x)

not_area = []

for x in range(len(pre_covid_times)):
    if pre_covid_times["Area Type"][x] != "Counties & UAs (from Apr 2021)" or pre_covid_times["Sex"][x] != "Persons":
        not_area.append(x)

pre_covid_regions = pre_covid_times.drop(not_region)
pre_covid_areas = pre_covid_times.drop(not_area)
pre_covid_regions.reset_index(drop=True, inplace=True)
pre_covid_areas.reset_index(drop=True, inplace=True)
pre_covid_regions.drop(columns = ["Sex", "Category", "Parent Name", "Area Type", "Compared to Region value or percentiles"], inplace = True)
pre_covid_areas.drop(columns = ["Sex", "Category", "Area Type"], inplace = True)

In [18]:
covid_regions.head()

,Area Name,Time period,Value,Count,Compared to England value or percentiles
0,North East region,2019 - 21,12.950347,900.0,Worse
1,North West region,2019 - 21,11.368747,2177.0,Worse
2,Yorkshire and the Humber region,2019 - 21,12.548817,1799.0,Worse
3,East Midlands region,2019 - 21,10.348662,1317.0,Similar
4,West Midlands region,2019 - 21,10.719293,1645.0,Similar

In [19]:
pre_covid_regions.head()

,Area Name,Time period,Value,Count,Compared to England value or percentiles
0,North East region,2017 - 19,11.620744,801.0,Worse
1,North West region,2017 - 19,10.647795,2025.0,Worse
2,Yorkshire and the Humber region,2017 - 19,11.966742,1699.0,Worse
3,East Midlands region,2017 - 19,9.515418,1197.0,Better
4,West Midlands region,2017 - 19,10.196134,1548.0,Similar

In [20]:
covid_areas.head()

,Parent Name,Area Name,Time period,Value,Count,Compared to England value or percentiles,Compared to Region value or percentiles
0,North East region,Hartlepool,2019 - 21,14.667019,36.0,Similar,Similar
1,North East region,Middlesbrough,2019 - 21,14.879852,54.0,Worse,Similar
2,North East region,Redcar and Cleveland,2019 - 21,19.750601,69.0,Worse,Worse
3,North East region,Stockton-on-Tees,2019 - 21,10.206445,52.0,Similar,Similar
4,North East region,Darlington,2019 - 21,16.598023,47.0,Worse,Similar

In [21]:
pre_covid_areas.head()

,Parent Name,Area Name,Time period,Value,Count,Compared to England value or percentiles,Compared to Region value or percentiles
0,North East region,Hartlepool,2017 - 19,10.361530,26.0,Similar,Similar
1,North East region,Middlesbrough,2017 - 19,14.464680,49.0,Worse,Similar
2,North East region,Redcar and Cleveland,2017 - 19,13.538658,47.0,Similar,Similar
3,North East region,Stockton-on-Tees,2017 - 19,8.673680,45.0,Similar,Better
4,North East region,Darlington,2017 - 19,13.646433,38.0,Similar,Similar

In [22]:
#putting those into cvs
pre_covid_regions.to_csv("../CSVs/PreCovid_r.csv", index=False)
covid_regions.to_csv("../CSVs/DuringCovid_r.csv", index=False)
pre_covid_areas.to_csv("../CSVs/PreCovid_a.csv", index=False)
covid_areas.to_csv("../CSVs/DuringCovid_a.csv", index=False)

In [23]:
#getting rid of data not needed for specific question (gender) and making dataframes from that
not_gender = []

for x in range(len(pre_covid_times)):
    if pre_covid_times["Area Type"][x] != "England" or pd.isna(pre_covid_times["Category"][x]) == False or pre_covid_times["Sex"][x] == "Persons":
        not_gender.append(x)

pre_covid_gender = pre_covid_times.drop(not_gender)
pre_covid_gender.reset_index(drop=True, inplace=True)
pre_covid_gender.drop(columns = ["Parent Name", "Area Name", "Area Type", "Category", "Compared to England value or percentiles", "Compared to Region value or percentiles"], inplace=True)

not_gender = []

for x in range(len(covid_times)):
    if covid_times["Area Type"][x] != "England" or pd.isna(covid_times["Category"][x]) == False or covid_times["Sex"][x] == "Persons":
        not_gender.append(x)

covid_gender = covid_times.drop(not_gender)
covid_gender.reset_index(drop=True, inplace=True)
covid_gender.drop(columns = ["Parent Name", "Area Name", "Area Type", "Category", "Compared to England value or percentiles", "Compared to Region value or percentiles"], inplace=True)

In [24]:
pre_covid_gender

      Sex Time period  Value    Count
0    Male   2017 - 19   15.5  11145.0
1  Female   2017 - 19    4.9   3643.0

In [25]:
covid_gender

      Sex Time period      Value    Count
0    Male   2019 - 21  15.895012  11551.0
1  Female   2019 - 21   5.186628   3896.0

In [26]:
#putting those into cvs
pre_covid_gender.to_csv("../CSVs/PreCovid_g.csv", index=False)
covid_gender.to_csv("../CSVs/DuringCovid_g.csv", index=False)

In [27]:
#getting rid of data not needed for specific question (gender) and making dataframes from that
not_wealth = []

for x in range(len(pre_covid_times)):
    if pre_covid_times["Area Type"][x] != "England" or pd.isna(pre_covid_times["Category"][x]) == True or pre_covid_times["Sex"][x] == "Male" or pre_covid_times["Sex"][x] == "Female":
        not_wealth.append(x)

pre_covid_wealth = pre_covid_times.drop(not_wealth)
pre_covid_wealth.reset_index(drop=True, inplace=True)
pre_covid_wealth.drop(columns = ["Parent Name", "Area Name", "Area Type", "Sex", "Compared to Region value or percentiles"], inplace=True)

not_wealth = []

for x in range(len(covid_times)):
    if covid_times["Area Type"][x] != "England" or pd.isna(covid_times["Category"][x]) == True or covid_times["Sex"][x] == "Male" or pre_covid_times["Sex"][x] == "Female":
        not_wealth.append(x)

covid_wealth = covid_times.drop(not_wealth)
covid_wealth.reset_index(drop=True, inplace=True)
covid_wealth.drop(columns = ["Parent Name", "Area Name", "Area Type", "Sex", "Compared to Region value or percentiles"], inplace=True)

In [28]:
#there are multiple types of the same deprived decile (as there are multiple ways a counting)
pre_covid_wealth

,Category,Time period,Value,Count,Compared to England value or percentiles
0,Most deprived decile (IMD2019),2017 - 19,10.389242,1371.0,Similar
1,Second most deprived decile (IMD2019),2017 - 19,10.178776,918.0,Similar
2,Third more deprived decile (IMD2019),2017 - 19,10.537259,1324.0,Similar
3,Fourth more deprived decile (IMD2019),2017 - 19,10.143353,1195.0,Similar
4,Fifth more deprived decile (IMD2019),2017 - 19,10.462497,1435.0,Similar
5,Fifth less deprived decile (IMD2019),2017 - 19,10.882899,1536.0,Worse
6,Fourth less deprived decile (IMD2019),2017 - 19,10.131730,2085.0,Similar
7,Third less deprived decile (IMD2019),2017 - 19,10.527818,1902.0,Similar
8,Second least deprived decile (IMD2019),2017 - 19,9.292926,2009.0,Better
9,Least deprived decile (IMD2019),2017 - 19,8.783976,1013.0,Better
10,Most deprived decile,2017 - 19,14.099039,1952.0,Worse
11,Second most deprived decile,2017 - 19,11.793167,1700.0,Worse
12,Third more deprived decile,2017 - 19,11.306501,1681.0,Worse
13,Fourth more deprived decile,2017 - 19,10.659038,1608.0,Worse
14,Fifth more deprived decile,2017 - 19,10.212313,1532.0,Similar
15,Fifth less deprived decile,2017 - 19,9.587735,1452.0,Better
16,Fourth less deprived decile,2017 - 19,9.061730,1342.0,Better
17,Third less deprived decile,2017 - 19,8.579002,1264.0,Better
18,Second least deprived decile,2017 - 19,8.274839,1201.0,Better
19,Least deprived decile,2017 - 19,7.416980,1056.0,Better
20,Most deprived decile (IMD2019),2017 - 19,10.154142,2076.0,Similar
21,Second most deprived decile (IMD2019),2017 - 19,11.226886,2394.0,Worse
22,Third more deprived decile (IMD2019),2017 - 19,9.947940,1808.0,Similar
23,Fourth more deprived decile (IMD2019),2017 - 19,11.285971,1542.0,Worse
24,Fifth more deprived decile (IMD2019),2017 - 19,10.319099,1288.0,Similar
25,Fifth less deprived decile (IMD2019),2017 - 19,10.215413,1480.0,Similar
26,Fourth less deprived decile (IMD2019),2017 - 19,9.529272,1200.0,Better
27,Third less deprived decile (IMD2019),2017 - 19,8.755494,1033.0,Better
28,Second least deprived decile (IMD2019),2017 - 19,9.614098,986.0,Similar
29,Least deprived decile (IMD2019),2017 - 19,8.935311,981.0,Better

In [29]:
covid_wealth

,Category,Time period,Value,Count,Compared to England value or percentiles
0,Most deprived decile (IMD2019),2019 - 21,10.992856,1488.0,Similar
1,Second most deprived decile (IMD2019),2019 - 21,10.632646,972.0,Similar
2,Third more deprived decile (IMD2019),2019 - 21,10.740648,1372.0,Similar
3,Fourth more deprived decile (IMD2019),2019 - 21,10.223478,1208.0,Similar
4,Fifth more deprived decile (IMD2019),2019 - 21,10.452282,1451.0,Similar
5,Fifth less deprived decile (IMD2019),2019 - 21,10.905408,1653.0,Similar
6,Fourth less deprived decile (IMD2019),2019 - 21,11.525656,2238.0,Worse
7,Third less deprived decile (IMD2019),2019 - 21,10.109969,1885.0,Similar
8,Second least deprived decile (IMD2019),2019 - 21,9.549752,2081.0,Better
9,Least deprived decile (IMD2019),2019 - 21,9.425460,1099.0,Better
10,Most deprived decile (IMD2019),2019 - 21,10.557198,2107.0,Similar
11,Second most deprived decile (IMD2019),2019 - 21,11.726642,2545.0,Worse
12,Third more deprived decile (IMD2019),2019 - 21,9.824971,1811.0,Better
13,Fourth more deprived decile (IMD2019),2019 - 21,11.457736,1570.0,Worse
14,Fifth more deprived decile (IMD2019),2019 - 21,10.957994,1461.0,Similar
15,Fifth less deprived decile (IMD2019),2019 - 21,10.599100,1591.0,Similar
16,Fourth less deprived decile (IMD2019),2019 - 21,9.729617,1238.0,Better
17,Third less deprived decile (IMD2019),2019 - 21,9.332682,1091.0,Better
18,Second least deprived decile (IMD2019),2019 - 21,9.603519,998.0,Better
19,Least deprived decile (IMD2019),2019 - 21,9.579676,1035.0,Better

In [30]:
#index 10 to 19 is where the category is named something different for pre-covid data, so rename
pre_covid_wealth.iloc[[10], 0] = "Most deprived decile (IMD2019)"
pre_covid_wealth.iloc[[11], 0] = "Second most deprived decile (IMD2019)"
pre_covid_wealth.iloc[[12], 0] = "Third more deprived decile (IMD2019)"
pre_covid_wealth.iloc[[13], 0] = "Fourth more deprived decile (IMD2019)"
pre_covid_wealth.iloc[[14], 0] = "Fifth less deprived decile (IMD2019)"
pre_covid_wealth.iloc[[15], 0] = "Fifth more deprived decile (IMD2019)"
pre_covid_wealth.iloc[[16], 0] = "Fourth less deprived decile (IMD2019)"
pre_covid_wealth.iloc[[17], 0] = "Third less deprived decile (IMD2019)"
pre_covid_wealth.iloc[[18], 0] = "Second least deprived decile (IMD2019)"
pre_covid_wealth.iloc[[19], 0] = "Least deprived decile (IMD2019)"

In [31]:
pre_covid_wealth

,Category,Time period,Value,Count,Compared to England value or percentiles
0,Most deprived decile (IMD2019),2017 - 19,10.389242,1371.0,Similar
1,Second most deprived decile (IMD2019),2017 - 19,10.178776,918.0,Similar
2,Third more deprived decile (IMD2019),2017 - 19,10.537259,1324.0,Similar
3,Fourth more deprived decile (IMD2019),2017 - 19,10.143353,1195.0,Similar
4,Fifth more deprived decile (IMD2019),2017 - 19,10.462497,1435.0,Similar
5,Fifth less deprived decile (IMD2019),2017 - 19,10.882899,1536.0,Worse
6,Fourth less deprived decile (IMD2019),2017 - 19,10.131730,2085.0,Similar
7,Third less deprived decile (IMD2019),2017 - 19,10.527818,1902.0,Similar
8,Second least deprived decile (IMD2019),2017 - 19,9.292926,2009.0,Better
9,Least deprived decile (IMD2019),2017 - 19,8.783976,1013.0,Better
10,Most deprived decile (IMD2019),2017 - 19,14.099039,1952.0,Worse
11,Second most deprived decile (IMD2019),2017 - 19,11.793167,1700.0,Worse
12,Third more deprived decile (IMD2019),2017 - 19,11.306501,1681.0,Worse
13,Fourth more deprived decile (IMD2019),2017 - 19,10.659038,1608.0,Worse
14,Fifth less deprived decile (IMD2019),2017 - 19,10.212313,1532.0,Similar
15,Fifth more deprived decile (IMD2019),2017 - 19,9.587735,1452.0,Better
16,Fourth less deprived decile (IMD2019),2017 - 19,9.061730,1342.0,Better
17,Third less deprived decile (IMD2019),2017 - 19,8.579002,1264.0,Better
18,Second least deprived decile (IMD2019),2017 - 19,8.274839,1201.0,Better
19,Least deprived decile (IMD2019),2017 - 19,7.416980,1056.0,Better
20,Most deprived decile (IMD2019),2017 - 19,10.154142,2076.0,Similar
21,Second most deprived decile (IMD2019),2017 - 19,11.226886,2394.0,Worse
22,Third more deprived decile (IMD2019),2017 - 19,9.947940,1808.0,Similar
23,Fourth more deprived decile (IMD2019),2017 - 19,11.285971,1542.0,Worse
24,Fifth more deprived decile (IMD2019),2017 - 19,10.319099,1288.0,Similar
25,Fifth less deprived decile (IMD2019),2017 - 19,10.215413,1480.0,Similar
26,Fourth less deprived decile (IMD2019),2017 - 19,9.529272,1200.0,Better
27,Third less deprived decile (IMD2019),2017 - 19,8.755494,1033.0,Better
28,Second least deprived decile (IMD2019),2017 - 19,9.614098,986.0,Similar
29,Least deprived decile (IMD2019),2017 - 19,8.935311,981.0,Better

In [32]:
#make a new dataframe for the average data
pre_covid_wealth2 = pre_covid_wealth.groupby("Category").mean()
covid_wealth2 = pre_covid_wealth.groupby("Category").mean()

In [33]:
pre_covid_wealth2

                                            Value        Count
Category
Fifth less deprived decile (IMD2019)    10.436875  1516.000000
Fifth more deprived decile (IMD2019)    10.123110  1391.666667
Fourth less deprived decile (IMD2019)    9.574244  1542.333333
Fourth more deprived decile (IMD2019)   10.696121  1448.333333
Least deprived decile (IMD2019)          8.378755  1016.666667
Most deprived decile (IMD2019)          11.547475  1799.666667
Second least deprived decile (IMD2019)   9.060621  1398.666667
Second most deprived decile (IMD2019)   11.066276  1670.666667
Third less deprived decile (IMD2019)     9.287438  1399.666667
Third more deprived decile (IMD2019)    10.597233  1604.333333

In [34]:
covid_wealth2

                                            Value        Count
Category
Fifth less deprived decile (IMD2019)    10.436875  1516.000000
Fifth more deprived decile (IMD2019)    10.123110  1391.666667
Fourth less deprived decile (IMD2019)    9.574244  1542.333333
Fourth more deprived decile (IMD2019)   10.696121  1448.333333
Least deprived decile (IMD2019)          8.378755  1016.666667
Most deprived decile (IMD2019)          11.547475  1799.666667
Second least deprived decile (IMD2019)   9.060621  1398.666667
Second most deprived decile (IMD2019)   11.066276  1670.666667
Third less deprived decile (IMD2019)     9.287438  1399.666667
Third more deprived decile (IMD2019)    10.597233  1604.333333

In [36]:
#putting those into cvs
pre_covid_wealth2.to_csv("../CSVs/PreCovid_w.csv")
covid_wealth2.to_csv("../CSVs/DuringCovid_w.csv")